Repository yourssu/Handy-React, pull requests merged in 2023-10, with the labels that each got.

#6 feat: Badge 구현
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.style.ts
  src/components/Badge/Badge.tsx
  src/components/Badge/Badge.type.ts
  src/components/Badge/index.ts
Labels: enhancement

#10 feat: PlainButton 구현
  src/components/PlainButton/PlainButton.stories.tsx
  src/components/PlainButton/PlainButton.style.ts
  src/components/PlainButton/PlainButton.tsx
  src/components/PlainButton/PlainButton.type.ts
  src/components/PlainButton/index.ts
  src/components/index.ts
Labels: enhancement

#9 feat: CheckBox 구현
  src/components/BoxButton/BoxButton.stories.tsx
  src/components/CheckBox/CheckBox.stories.tsx
  src/components/CheckBox/CheckBox.style.ts
  src/components/CheckBox/CheckBox.tsx
  src/components/CheckBox/CheckBox.type.ts
  src/components/CheckBox/index.ts
  src/components/PlainButton/PlainButton.stories.tsx
  src/components/index.ts
Labels: enhancement, feat

#13 docs: update request template
  .github/pull_request_template.md
Labels: docs
