Repository yourssu/Handy-React, pull requests merged in 2024-03, with the labels that each got.

#41 feat: Typo 수정
  src/components/ListItem/ListItem.style.ts
  src/components/TextField/TextField.style.ts
  src/style/foundation/typo/typo.ts
  src/style/foundation/typo/typo.type.ts
Labels: feat

#44 feat: Color 수정
  src/style/foundation/color/baseColor/baseColor.type.ts
  src/style/foundation/color/baseColor/baseColorPalette.ts
  src/style/foundation/color/semanticColor/semanticColor.type.ts
  src/style/foundation/color/semanticColor/semanticColorPalette.ts
Labels: fix, feat

#51 config: publish to npm in workflows
  .github/workflows/deploy.yml
  .gitignore
  package.json
Labels: config

#56 chore: yarn to pnpm, storybook version upgrade
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/style/foundation/foundation.mdx
  yarn.lock
Labels: chore

#57 fix: tsc error in Toast.stories.tsx
  src/components/Toast/Toast.stories.tsx
Labels: bug, fix

#58 docs: add storybook color palette
  src/style/foundation/color/color.mdx
  src/style/foundation/color/semanticColor/semanticColorPalette.ts
  src/style/foundation/foundation.mdx
  src/style/foundation/icons/IconDocs.md
  src/style/foundation/icons/icons.stories.tsx
  src/style/foundation/typo/Typo.stories.tsx
  src/style/foundation/typo/TypoDocs.md
Labels: docs, refactor
