Repository yourssu/Handy-React, pull requests merged in 2024-05, with the labels that each got.

#81 feat: add extension recommendations
  .vscode/extensions.json
  src/components/Toast/Toast.style.ts
Labels: feat

#84 refactor: 웹에 맞게 Toast.style 수정
  src/components/Toast/HookSource.md
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.style.ts
  src/components/Toast/Toast.tsx
  src/components/Toast/Toast.type.ts
Labels: refactor

#85 feat: config react docgen typescript
  .storybook/main.ts
Labels: feat, docs

#87 refactor: `OnlyBGColor` 조건 수정
  src/components/Badge/Badge.type.ts
  src/style/foundation/color/semanticColor/semanticColor.type.ts
Labels: refactor

#88 fix: release template
  .github/release.yml
Labels: fix

#89 chore: update version v1.1.0
  package.json
Labels: chore

#91 fix: release-template
  .github/release.yml
Labels: bug, fix

#93 refactor: setting default value in PasswordTextField
  src/components/TextField/PasswordTextField/PasswordTextField.tsx
Labels: refactor

#94 chore: update version v1.1.1
  package.json
Labels: chore

#99 fix: load spoqa font with webfontloader
  index.html
  package.json
  pnpm-lock.yaml
  src/style/globalStyle/GlobalStyle.tsx
Labels: bug, fix

#97 fix: duplicate class name in suffix icon
  src/components/TextField/PasswordTextField/PasswordTextField.tsx
  src/components/TextField/SearchTextField/SearchTextField.tsx
  src/components/TextField/SimpleTextField/SimpleTextField.tsx
  src/components/TextField/SuffixTextField/SuffixTextField.type.ts
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
Labels: bug, fix

#103 fix: shoving searchPrefix in SearchTextField
  src/components/TextField/SearchTextField/SearchTextField.tsx
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
Labels: bug, fix

#95 v1.1.1
  .github/release.yml
  index.html
  package.json
  pnpm-lock.yaml
  src/components/TextField/PasswordTextField/PasswordTextField.tsx
  src/components/TextField/SearchTextField/SearchTextField.tsx
  src/components/TextField/SimpleTextField/SimpleTextField.tsx
  src/components/TextField/SuffixTextField/SuffixTextField.type.ts
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.style.ts
  src/style/globalStyle/GlobalStyle.tsx
Labels: deploy

#107 fix: suffix icon appears when the TextField is disabled
  src/components/TextField/TextField.style.ts
Labels: bug, fix

#109 feat: apply forwardRef in TextField
  src/components/TextField/PasswordTextField/PasswordTextField.tsx
  src/components/TextField/SearchTextField/SearchTextField.tsx
  src/components/TextField/SimpleTextField/SimpleTextField.tsx
  src/components/TextField/SuffixTextField/SuffixTextField.tsx
  src/components/TextField/TextField.tsx
Labels: feat

#110 chore: update version v1.1.2
  package.json
Labels: chore
